### ISSUE TITLE
Support composer.json in subfolder

### ISSUE THREAD

**Issue by jthomaschewski** [jaguadoromero/vscode-php-create-class#1]
It would be great if composer.json could be manually specified or (even better) automatically detected by recursively finding the closest parent folder containing a composer.json.

e.g. for monorepo directory structure like:
```
package1/composer.json
package2/composer.json
```

**Comment by jaguadoromero** [comment]
I have released an update with this feature.
Now, the right composer.json will be detected by recursively finding the closest parent folder that contains a composer.json file.
