### ISSUE TITLE
a suggestion perhaps

### ISSUE THREAD

**Issue by Arifursdev** [jaguadoromero/vscode-php-create-class#11]
so i tried the extension in VSCode
so it doesn't create class, enum , trait or anything unless there is an composer.json file,

so is it possible to only show these 4 options 
[https://i.imgur.com/whLAhcv.png](url)
only when the current directory contains a composer.json file?

Thanks!

**Comment by jaguadoromero** [comment]
@Arifursdev Now the extension is only activated when finds composer.json file in workspace
