### ISSUE TITLE
Add boilerplate code to an open empty file

### ISSUE THREAD

**Issue by shops-united-jkroonen** [jaguadoromero/vscode-php-create-class#13]
The plug-in very helpful, thank you! Is it possible to add the boilerplate code to an open empty file, instead of opening finder? 

**Explanation**

1. Open an existing empty file

<img width="621" alt="Screen Shot 2022-09-01 at 15 03 59" src="https://user-images.githubusercontent.com/104895609/187921183-ef3eb6f1-ef52-4685-a515-ea9bb98b0455.png">
  
3. Open command palette

<img width="956" alt="Screen Shot 2022-09-01 at 15 07 57" src="https://user-images.githubusercontent.com/104895609/187921376-475a1bff-aeb0-40fa-a167-7887a378ad46.png">
  
4. Select the option PHP: New PHP <type>

<img width="920" alt="Screen Shot 2022-09-01 at 15 10 30" src="https://user-images.githubusercontent.com/104895609/187922007-41e96c70-8adb-4068-bd15-b768d754ae88.png">
  
5. Add the boilerplate code to the empty openend file

<img width="760" alt="Screen Shot 2022-09-01 at 15 11 44" src="https://user-images.githubusercontent.com/104895609/187922191-9c9a7a8a-ec29-400f-a258-50d9addf5a6e.png">

**Comment by jaguadoromero** [comment]
@shops-united-jkroonen In version 1.13.0 has been added the ability to generate boilerplate code from comands (Generate Class code, Generate Interface code, Generate Trait code and Generate Enum code)
