### ISSUE TITLE
Please add an option to configure composer root path

### ISSUE THREAD

**Issue by ktogias** [jaguadoromero/vscode-php-create-class#14]
Hey, @jaguadoromero 

Thank you for this useful extension!

After c32bbd4bce92ddd9946211cc3b24d33a4cb7e8e4 the plugin is disabled for projects with composer.json in a subfolder instead of project root. 

Can you please add an option to configure the project root folder?

Thanks!

**Comment by saifrahmania** [comment]
the instructions on the extension page are not clear. side by side when we try to create a new class that time the error message says that the command "phpCreateClass.createClass" is not found. 
![image](https://user-images.githubusercontent.com/89687720/195874168-d8d95a61-b5fa-4351-81e8-a8fac00aca67.png)
now my question where should I add these commands? please give us proper instructions

**Comment by jaguadoromero** [comment]
@ktogias  Since version 1.11.0, the plugin is activated also when composer.json is present in a subfolder and detects the correct namespace
