### ISSUE TITLE
Extension does nothing

### ISSUE THREAD

**Issue by twinpigs** [jaguadoromero/vscode-php-create-class#18]
Nothing happens when I click context menu "New PHP Class". When I run Generate Class code from console error modal window says "Command 'PHP:Generate Class code' resulted in an error (Cannot read properties of undefined (reading 'trim')".

Extension: v1.13.1

VSCode:
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:57:40.428Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-58-generic
Sandboxed: No

**Comment by jaguadoromero** [comment]
@twinpigs try if your problem is solved in new 1.15.0 version

**Comment by jaguadoromero** [comment]
I close this issue for inactivity
