### ISSUE TITLE
PHP Create Class: Strict Types not working

### ISSUE THREAD

**Issue by murugappanrm** [jaguadoromero/vscode-php-create-class#19]
I tried to to set the Strict Types setting in VSCode but i get this error displayed

"Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again."

Please help as this essential for me using PHP 8.1.

**Comment by jaguadoromero** [comment]
@murugappanrm Not seems related to this extension, but an error in your "settings.json" configuration file structure. Open the file and check it as the error message suggests.

**Comment by murugappanrm** [comment]
@jaguadoromero 

Ok. I will test it on another PC which should not have any errors as that was installed fresh and serves as backup.

**Comment by murugappanrm** [comment]
Hi @jaguadoromero 

You were right, I found that the one of the Laravel extensions placed a setting without the opening curly bracket. Fixed that and it works great. Thank you so much.
