### ISSUE TITLE
The composer.json file could not be read

### ISSUE THREAD

**Issue by KaloyJS** [jaguadoromero/vscode-php-create-class#2]
Hi there, I just installed this extension and I could not create a new PHP class at all. While composer.json is present in main directory.
Error message: the composer.json file could not be read

 Thanks in advance

**Comment by jaguadoromero** [comment]
It is possible that your composer.json not contains an "autoload" entry and only contains "autoload-dev" entry?
This case I had not contemplated, but I will fix it.

**Comment by jaguadoromero** [comment]
@KaloyJS I have released an update with some fixes and checks when reading composer.json file.

If error persists, please check that composer.json file not contains any syntax error (like trailing comma at last element in an array)
