### ISSUE TITLE
Incorrect namespace in version 15.1

### ISSUE THREAD

**Issue by dmitrach** [jaguadoromero/vscode-php-create-class#21]
I've got the follow namespace in version 15.1:

```php
namespace App\Module/Manager;
```

In the previous version 13.1 I get the correct namespace: ```namespace App\Module\Manager; ```

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:47:05.613Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-41-generic
Sandboxed: Yes

**Comment by jaguadoromero** [comment]
@dmitrach I just published an update with a fix for this problem. Sorry for the inconveniences.
