### ISSUE TITLE
[Feature Request] Group options in submenu

### ISSUE THREAD

**Issue by artrz** [jaguadoromero/vscode-php-create-class#25]
It would be nice to have all the options inside a submenu. Something like "New PHP File..." would be consistent with "New File..." while and keeping the menu tidy.

**Comment by artrz** [comment]
@jaguadoromero are you open to receive a PR to implement this as an option?

**Comment by jaguadoromero** [comment]
@artrz of course, no problem ;)

**Comment by jaguadoromero** [comment]
@artrz since it was a small change, I have done it myself and it is already implemented in the latest version ;)

**Comment by artrz** [comment]
Awesome! Thanks @jaguadoromero !
