### ISSUE TITLE
[Bug] Unable to create class

### ISSUE THREAD

**Issue by artrz** [jaguadoromero/vscode-php-create-class#26]
After updating to v1.17.0 I'm unable to create classes. Then I configured `"phpCreateClass.composerFilePath": "./composer.json"` to explicitly set the location and when trying to create a class I'm getting "The namespace could not be resolved." After this there's a weird behavior: If after unsuccessfully trying to create a class file I manually close the error message by click on its close button, the file gets created after the alert disappears, however if I close the error message by pressing ESC nothing gets created, and after trying to create a different class, the previous requested class file gets created and a new error alert appears.

**Comment by viejalospelos** [comment]
Same issue over here; after upgrading this morning to last version (1.17), it's impossible to create classes, enums, interfaces or traits; when I try to create a class, the box where I have to insert the name of that class appears but the extension doesn't create the file.

**Comment by jaguadoromero** [comment]
@artrz If your `composer.json` file is in the project root folder (the most common case) you don't have to set the `composerFilePath` setting, just leave it empty.

On the other hand, the setting does not accept start with `./`. 
If, for example, you have the `composer.json` file in `libs/composer/composer.json` (relative to root project folder), add it as is in setting.

**Comment by jaguadoromero** [comment]
@viejalospelos I have tried and it works correctly for me. 
Do you have any value defined in **Composer File Path** setting?

**Comment by jaguadoromero** [comment]
@artrz @viejalospelos
I just published a fix, v1.17.1.

It seems that the problem was when the extension was updated but your settings file still does not contain the new Composer File Path setting.

**Comment by artrz** [comment]
Thanks @jaguadoromero! It's working now. Just to clarify, it was failing without any custom config and on a project with composer at root. I added the setting just to see if that could fix the issue.

**Comment by viejalospelos** [comment]
It works properly again with version 17.1, thanks
