### ISSUE TITLE
The upgrade to version 1.16 and 1.17 broken

### ISSUE THREAD

**Issue by murugappanrm** [jaguadoromero/vscode-php-create-class#27]
Hi,

When i upgrade to version 1.17.1, the classes created are generating wrong namespace. See screencap below. I reverted to version 1.15 and it works fine. Please check.

![Create Class Error](https://github.com/jaguadoromero/vscode-php-create-class/assets/63133893/2478e773-1fb0-4f37-9099-2a0662e596c1)

**Comment by jaguadoromero** [comment]
@murugappanrm Fixed in 1.17.2. The problem was that Windows handles the folder separator differently than Linux/MacOS.

**Comment by murugappanrm** [comment]
Ok will test it out. Thank you.

**Comment by murugappanrm** [comment]
Hi @jaguadoromero ,

Its working fine now. Thank you so much.

**Comment by murugappanrm** [comment]
@jaguadoromero 

Have to reopen this issue again. I spoke too soon, My apologize. If the class is created under a sub-folder, it works. But if it created under the main folder the same error occurs. See screencap below:

![Create Class Error](https://github.com/jaguadoromero/vscode-php-create-class/assets/63133893/a6a24df9-9cca-466b-ab28-80c232bd4669)

**Comment by jaguadoromero** [comment]
@murugappanrm You're right. I have fixed it in 1.17.3., sorry for the inconveniences, my development machine is not Windows and the folder separator that handles Windows being different from Unix style is a bit headache in dealing with paths

**Comment by murugappanrm** [comment]
Hi @jaguadoromero 

No need to apologize. This is simplest and best extension i have used in vscode. It saved me so much clicks and typo. Great job. Love to some good extensions for refactoring in php. The current ones are so flawed. 

Thank you so much.
